// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SayHello.proto

package com.netty.grpc.example1;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protobuf.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_name = 1;</code>
   */
  String getUserName();
  /**
   * <code>string user_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
