// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SayHello.proto

package com.netty.grpc.example1;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protobuf.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string real_name = 1;</code>
   */
  String getRealName();
  /**
   * <code>string real_name = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
