// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SayHello.proto

package com.netty.grpc.example1;

public final class SayHello {
  private SayHello() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protobuf_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016SayHello.proto\022\014com.protobuf\"\036\n\tMyRequ" +
      "est\022\021\n\tuser_name\030\001 \001(\t\"\037\n\nMyResponse\022\021\n\t" +
      "real_name\030\001 \001(\t2\230\001\n\017SayHelloService\022?\n\010S" +
      "ayHello\022\027.com.protobuf.MyRequest\032\030.com.p" +
      "rotobuf.MyResponse\"\000\022D\n\rSayHelloAgain\022\027." +
      "com.protobuf.MyRequest\032\030.com.protobuf.My" +
      "Response\"\000B%\n\027com.netty.grpc.example1B\010S" +
      "ayHelloP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_protobuf_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protobuf_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_MyRequest_descriptor,
        new String[] { "UserName", });
    internal_static_com_protobuf_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protobuf_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protobuf_MyResponse_descriptor,
        new String[] { "RealName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
